Numpy Arrays: 
>Copy,view
>Shape,reshape
>Iterating
>Joining and Splitting
>Searching and Sorting
>Universal Functions


In [2]:
import numpy as np

arr = np.array([1,2,3,4,5])

newarr = arr.copy()

print('Original array')
print(arr)
print('New Array')
print(newarr)

newarr[2]=10

print('Original array after Change')
print(arr)
print('New Array after Change')
print(newarr)



Original array
[1 2 3 4 5]
New Array
[1 2 3 4 5]
Original array after Change
[1 2 3 4 5]
New Array after Change
[ 1  2 10  4  5]


In [3]:
x = arr.view()

x[2] =10
print(x)

print(arr)

[ 1  2 10  4  5]
[ 1  2 10  4  5]


FOR ARRAYS, [:] DOES NOT WORK TO COPY THE ARRAY. THERE IS NO DIFFRENCE BETWEEN arr = newarr and  arr = newarr[:],BOTH STORE AN IMAGE OF THE ORIGINAL ARRAY.

Copy works like arr = newarr[:] for list
View works like arr = newarr

View saves an Image of the array in a new array. Changing this image will also change the original array.

Base attribute refers to the original array of a given array  I'e is 
x = y
then x is base of y. 

In [4]:
#Copy vs View Base
arr = np.array([1,2,3,4,5])

x=arr.copy()
y=arr.view()

print(x.base)
print(y.base)


None
[1 2 3 4 5]


In [5]:
arr1 = np.array(1)
arr2 = np.array([1,2,3,4])
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr4 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print(arr1.shape)
print(arr2.shape)
print(arr3.shape)
print(arr4.shape)

()
(4,)
(3, 3)
(2, 2, 2)


Reshape matrix. The diemnsions of the matrix can be changed then copied. Will not change the original matrix.
The the product of the dimensions shoul be equal to the number of ellements given, 

In [6]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr1 =arr.reshape(3,4)
newarr2 =arr.reshape(3,2,2)
print('3 X 4')
print(newarr1,'\n')
print('3 X 2 X 2')
print(newarr2)

3 X 4
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

3 X 2 X 2
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [7]:
# change 3x4 to 4x3

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(arr,'\n')

newarr= arr.reshape(4,3)

print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


We can pass -1 one of the dimensions.It will automatically calcutlate that dimension. It will onle work if passed to 1 ofthe chosen dimensions.

In [8]:
print(newarr,'\n')

made_3d = newarr.reshape(2,2,-1)

print(made_3d)

flattened = newarr.reshape(-1)
print(flattened)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


Iterating across array

In [14]:
arr = np.array([[1,2,3],[4,5,6]])
#x = arr[1,2]
#print(x*x)

#usein forloop to iterate

for x in arr:
   for y in x:
      val = y
      print('Square of index ',y,' in array is:',val*val,'\n')



Square of index  1  is: 1 

Square of index  2  is: 4 

Square of index  3  is: 9 

Square of index  4  is: 16 

Square of index  5  is: 25 

Square of index  6  is: 36 



In [44]:
def factorial(number:int):
    number = abs(number)
    temp_val = 1
    for i in range(1,number+1):
         temp_val *= i
    return(temp_val)

#print(factorial(1)) 

arr = np.array([1,2,3,4,5,6,7,8,9])
arr = arr.reshape(3,-1)

for i in arr:
    for j in i:
        print(factorial(j))
        




1
2
6
24
120
720
5040
40320
362880


np.nditer will allow the elements of matrix to be  iterated on .

In [49]:
arr = np.array([[1,2],[3,4]])


for i in np.nditer(arr):
    print(i)

1
2
3
4


Joining Python arrays 
np.concatenate()
np.stack()
np.vstack() Vertical
np.dstack() Depth
np.hstack() Horizental

columns = axis=1
row     = axis=0

In [53]:
arr1 =np.array([[1,2],[3,4]])
arr2 =np.array([[5,6],[7,8]])

arr_conc = np.concatenate((arr1,arr2),axis=1)

print(arr_conc)
arr_conc = np.concatenate((arr1,arr2),axis=0)

print(arr_conc)

#concatenate joins the matrices

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [61]:
#stack
print(arr1)

print('-_________________________________________________________________-')
arr_stack = np.stack((arr1,arr2),axis=1)

print(arr_stack)

print('-_________________________________________________________________-')

arr_stack = np.stack((arr1,arr2),axis=0)

print(arr_stack)




[[1 2]
 [3 4]]
-_________________________________________________________________-
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
-_________________________________________________________________-
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [66]:
arr_vstack = np.vstack((arr1,arr2))

print(arr_vstack)

arr_hstack = np.hstack((arr1,arr2))

print(arr_hstack)

arr_dstack = np.dstack((arr1,arr2),)

print(arr_dstack)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


Splut will not retun an array, but a list of the splt arrays

In [69]:
arr = np.array([1,2,3,4,5,6,7,8,9])

newarr = np.array_split(arr,2)

print(newarr)

[array([1, 2, 3, 4, 5]), array([6, 7, 8, 9])]


In [86]:
arr = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])

newarr = np.array_split(arr,2,axis=1)
print(newarr)

[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]])]


np.where() to find indexes where valye has occured

In [90]:
arr = np.array([1,2,3,4,5,5,6,5,5,5,55,5])

x = np.where(arr == 5)

print(x)

(array([ 4,  5,  7,  8,  9, 11], dtype=int64),)


In [92]:
arr = np.array([[2,4],[3,1]])

x = np.sort(arr)

print(x)

#search sorted can only return index if values are sorted

 


[[2 4]
 [1 3]]
