Array Collection of Dtaa of Interger Flationg Value

In python, storing large data in list tuple and Set is inefficient.We instead use Numpy package.


Arrays can be 1 dimensional like list or tuple, however, the can also be multple dimension. 

Python has an inbuilt importable array method, but numpy is better.

In [2]:
#Normal array
import array

cgpa = array.array('i',[2,2,4,4,5])
print(cgpa[0])

2


Arrays are stored in one continuous place in memory and are thus much faster to use.
List are stored in diffrent places in list. Array is thus more efficient and fatser.

Numpy Arrays are are faster and better. They are called ndarray.

In [3]:
import numpy

myarray = numpy.array([2,4,6,8,3,5,7])

print(myarray)

print(type(myarray))



[2 4 6 8 3 5 7]
<class 'numpy.ndarray'>


In [4]:
import numpy as np

myarray = np.array([2,4,6,8,3,5,7])


print(myarray)


print(type(myarray))

[2 4 6 8 3 5 7]
<class 'numpy.ndarray'>


Python will convert the entire array contents to the incompatible type. eg: [1,2,3,4,5,'a'] will be onverted in to  string

In [5]:
myarray_text = np.array([1,2,3,4,5,6,7,8,8,'a','b'])
print(myarray_text)

['1' '2' '3' '4' '5' '6' '7' '8' '8' 'a' 'b']


In [6]:
print(np.__version__)

1.26.3


In [7]:
#using tuple
my_tuple = np.array((1,2,3,4,5,6,7))
#Using Scalar (0-dimensional list)

my_scalar = np.array(2)
print(my_scalar)
print(type(my_scalar))

2
<class 'numpy.ndarray'>


In [8]:
#2d array

my2darray= np.array([[2,4,6],[7,3,9]])
print(my2darray)
print(my2darray[1][1])


[[2 4 6]
 [7 3 9]]
3


In [9]:
#3 dimensional array

my3darray = np.array([[[2,3],[4,5]],[[6,7],[8,9]],[[10,11],[12,13]]])

print(my3darray)

print(my3darray[1][0][1])
print(my2darray.ndim)

[[[ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]]]
7
2


In [13]:
my_3by4 = np.array([[1,2,3,4],
                    [4,5,6,7],
                    [7,8,9,10]])

print(my_3by4[1,3])

7


In [14]:
my_3by4 = np.mat([[1,2,3,4],
                    [4,5,6,7],
                    [7,8,9,10]])

In [20]:
my3darray = np.array([[[2,3,1],[4,5,1]],[[6,7,1],[8,9,1]],[[10,11,1],[12,13,1]]])
# array[height,row,column]
print(my3darray[-1,-1,-1])

1


Slicing 2d array


In [22]:
my_3by4 = np.mat([[1,2,3,4],
                    [4,5,6,7],
                    [7,8,9,10]])
x = my_3by4[2,:3]
print(x)

[[7 8 9]]


In [30]:
my_array = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(my_array[0:2,4])

[ 5 10]


In [29]:
my_array = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(my_array[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [44]:
assingment = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

print(assingment,'\n')

x = assingment[:,1:3]
y = assingment[1:3,:]
z = assingment[1:3,1:3]
print(x,'\n')
print(y,'\n')

print(z)

assingment.dtype

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]] 

[[ 5  6  7  8]
 [ 9 10 11 12]] 

[[ 6  7]
 [10 11]]


dtype('int32')

In [47]:
my_text_array = np.array(['a','A','c'])

my_text_array.dtype

dtype('<U1')

In [60]:
test_array = np.array([1,2,3,4,5,6,7,8,9])
print(test_array.dtype)
X = test_array.astype('u8')
print(X.dtype)

int32
uint64


In [22]:

count = 0
x = ''
y = ''
while count<5:
    count+= 1
    x=''
    y=''
    for j in range(5-count):
        y+=' '
    for i in range(count):
        x +='* '    
        
    print(y+x)         


    * 
   * * 
  * * * 
 * * * * 
* * * * * 
