Numpy: Numerecial python and understanding its various dimensions 

In [1]:
import numpy as np 

arr = np.array([1,2,3,4,5]) #outcome will be assigned as list 

print(arr)

[1 2 3 4 5]


In [2]:
#we  can also import numpy without alias 

import numpy

arr1 = numpy.array([2,3,45,6,7])

print(arr1)

[ 2  3 45  6  7]


Dimensions of array : 0-d,1-d,.......to higher dimensional arrays 

In [4]:
#0-d 

import numpy as np

arr = np.array(500)

print(arr)

500


In [5]:
#1-d

arr1 = np.array([1,2,3,4,5])

print(arr1)

[1 2 3 4 5]


In [6]:
#2-d

arr2 = np.array([[1,2,3],
                 [4,5,6]])

print(arr2)

[[1 2 3]
 [4 5 6]]


In [11]:
#3-d

arr3 = np.array([[[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12]],])

print(arr3)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [13]:
#4-d

arr4 = np.array([[[[1,2,3,4,5],
                   [2,3,4,5,6],
                   [4,6,5,7,3,],
                   [74,44,56,78,90]]]])
print(arr4)
print(type(arr4))

[[[[ 1  2  3  4  5]
   [ 2  3  4  5  6]
   [ 4  6  5  7  3]
   [74 44 56 78 90]]]]
<class 'numpy.ndarray'>


identifying types of Dimensions: 

In [14]:
import numpy as np 

arr = np.array(500)
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[[[1,2,3,4,5],
                   [2,3,4,5,6],
                   [4,6,5,7,3,],
                   [74,44,56,78,90]]]])
arr3 = np.array([[[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12]],])

arr4 = np.array([[1,2,3],
                 [4,5,6]])

print(arr.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)

0
1
4
3
2
