Numpy: what is a numpy ? 
  - Numpy is a library 
  - the full form of numpy is numerical python 
  - it is used for working with arrays 

installation of numpy 

In [12]:
!pip install numpy

import of numpy and creation of arrays 

In [13]:
#simple importing of numpy 
import numpy

In [14]:
#importing of numpy by assigning an array with list, tuple arguments 

import numpy

arr = numpy.array([1,2,3,4,5,6,7])
arr1 = numpy.array((1,2,3,4,5,6)) #outcome will always come in list formate as array will only store its memomy in list data set 

print(arr)
print(arr1)



[1 2 3 4 5 6 7]
[1 2 3 4 5 6]


In [15]:
#importing numpy using an alias (nick-name): np, pd, ....etc as per users wish 

import numpy as np 

df = np.array([2,4,6,8,10])

print(df)

[ 2  4  6  8 10]


In [16]:
import numpy as pd 

obj = pd.array([3,5,7,9,11])

print(obj)

[ 3  5  7  9 11]


o-d arrray 

In [1]:
import numpy as np

d = np.array(45)
print(d)

45


1 - d array 

In [2]:
d1 = np.array([1,2,3,4,5])
print(d1)

[1 2 3 4 5]


2 - d array 

In [8]:


d2 = np.array([[1,2,3,4],
               [5,6,7,8]])

print(d2)

[[1 2 3 4]
 [5 6 7 8]]


3- d array 

In [11]:
d3 = np.array([[1,2,3],[4,5,6],
              [7,8,9],[10,11,12]])

print(d3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


4- dimension array 

In [12]:
d4 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]]])
print(d4)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


identifying various dimension through ndim method

In [15]:
import numpy as np


df = np.array(455)
df1 = np.array([1,2,3])
df2 = np.array([[1,2,3],
               [4,5,6]])
df3 = np.array([[[1,2,3],
                [4,5,6]],
               [[7,8,9],
                [10,11,12]]])
df4 = np.array([[[1,2],
                 [3,3]],
                [[4,4],
                 [5,5]]])
df5 = np.array([[[[1,2,3],
                  [1,2,3],
                  [1,2,3]]]])

print(df)
print(df1)
print(df2)
print(df3)
print(df4)
print(df5)

print(df.ndim)
print(df1.ndim)
print(df2.ndim)
print(df3.ndim)
print(df4.ndim)
print(df5.ndim)


455
[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[1 2]
  [3 3]]

 [[4 4]
  [5 5]]]
[[[[1 2 3]
   [1 2 3]
   [1 2 3]]]]
0
1
2
3
3
4
